@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"D:\professional software\IAR7.7\common\bin\cspybat" -f "E:\work\seekfree\freescale_work\传感器历程\总钻风\总钻风例程(V2版本)\例程\1.一幅图像采集完成触发中断\总钻风例程K60(OLED显示二值化图像)\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60FX_Debug.general.xcl" --backend -f "E:\work\seekfree\freescale_work\传感器历程\总钻风\总钻风例程(V2版本)\例程\1.一幅图像采集完成触发中断\总钻风例程K60(OLED显示二值化图像)\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60FX_Debug.driver.xcl" 

@echo off 
goto end 

:debugFile 

@echo on 

"D:\professional software\IAR7.7\common\bin\cspybat" -f "E:\work\seekfree\freescale_work\传感器历程\总钻风\总钻风例程(V2版本)\例程\1.一幅图像采集完成触发中断\总钻风例程K60(OLED显示二值化图像)\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60FX_Debug.general.xcl" "--debug_file=%~1" --backend -f "E:\work\seekfree\freescale_work\传感器历程\总钻风\总钻风例程(V2版本)\例程\1.一幅图像采集完成触发中断\总钻风例程K60(OLED显示二值化图像)\Projecct\IAR\program\settings\SeekFree_Kinetis.MK60FX_Debug.driver.xcl" 

@echo off 
:end